name: "CueBlox Build"
description: "CueBlox Build"
inputs:
  extraArgs:
    description: "Enforce Referential Integrity?"
    required: false
    default: ""
  directory:
    description: "Where is your blox.yaml?"
    required: false
    default: .
runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.directory }}
    - ${{ inputs.extraArgs }}
